#!/bin/bash

mkdir $1
cp data_helpers.py formula_and_sites.p magnetic_ordering_data.pt magnetic_ordering.py util_mag.py $1
cd $1

touch run_job.sh
echo "#!/bin/bash
#SBATCH -c 5
#SBATCH --mail-type=ALL
#SBATCH --gres=gpu:volta:1

source /etc/profile
cd /home/gridsan/sekim
module load anaconda/2022a
eval \"\$(conda shell.bash hook)\"
source .bashrc
conda activate /home/gridsan/sekim/.conda/envs/e3nn

cd magnetic-ordering/$1
python magnetic_ordering.py" > run_job.sh

